common:
  # Request headers to mimic browser
  headers:
    user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'
    sec_ch_ua: '"Chromium";v="134", "Not:A-Brand";v="24", "Brave";v="134"'
    sec_ch_ua_mobile: '?0'
    sec_ch_ua_platform: '"macOS"'

# Configuration for BLS Data Downloader
bls:
  # Base URL for downloading files
  base_url: 'https://download.bls.gov'

  # Scraping configuration
  scraping:
    directory_path: '/pub/time.series/pr/'
    file_regex_pattern: '(\d{1,2}/\d{1,2}/\d{4})\s+(\d{1,2}:\d{2}\s[APM]{2})\s+(\d+)\s+<a href=\"(.*?)\">(.*?)</a>'

  # Download configuration
  download:
    target_directory: &bls_target_dir 'data/bls/raw'  # Leave empty for current directory, or specify a full path like '/path/to/downloads/'
    max_workers: 3  # Concurrent download thread workers
  
  # File tracking configuration
  file_tracking:
    csv_directory: 'data/bls/tracker'  # Leave empty for current directory, or specify a full path like '/path/to/tracking/'
    csv_filename: 'downloaded_files.csv'

population:
  # Base URL for downloading US population data
  base_url: 'https://datausa.io/api/data?drilldowns=Nation&measures=Population'

  # Download configuration
  download:
    json_directory: &population_json_dir 'data/population/raw'
    json_filename: &population_json_filename 'population.json'
  
analysis:
  bls:
    download_dir: *bls_target_dir
    file_name: 'pr.data.0.Current'
  population:
    download_dir: *population_json_dir
    file_name: *population_json_filename